In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd

In [3]:
import torch
from torch import nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split

In [4]:
import numpy as np
import pandas as pd

In [211]:
butte = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_Butte.csv")
calaveras = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_Calaveras.csv")
dorado = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_Dorado.csv")
fresno = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_Fresno.csv")
humboldt = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_Humboldt.csv")
kern = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_KERN.csv")
lassen = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_Lassen.csv")
modoc = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_Modoc.csv")
nevada = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_Nevada.csv")
plumas = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_Plumas.csv")
riverside = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_Riverside.csv")
bernardino = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_San Bernardino.csv")
diego = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_San Diego.csv")
shasta = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_Shasta.csv")
siskiyou = pd.read_csv("/content/drive/MyDrive/Wildfire (1)/Datasets/merged_tp_precip_wind_fmc_Siskiyou.csv")

In [212]:

def append_dataframes(dataframes):
    if len(dataframes) == 0:
        return None
    elif len(dataframes) == 1:
        return dataframes[0]
    else:
        combined_df = pd.concat(dataframes, ignore_index=True)
        return combined_df


dataframes_list = [butte, calaveras, dorado, fresno, humboldt, kern, lassen, modoc, dorado, nevada, plumas, riverside, bernardino, diego, shasta, siskiyou]

fire_data = append_dataframes(dataframes_list)

In [7]:
butte.head(70)

Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  FIRE_SIZE FIRE_SIZE_CLASS  \
0              0             0         464        2.0               B   
1              1             1         465        1.0               B   
2              2             2         466       12.0               C   
3              3             3         467        0.1               A   
4              4             4         468      787.5               E   
..           ...           ...         ...        ...             ...   
65            65            65         529        0.5               B   
66            66            66         530        2.0               B   
67            67            67         531        2.0               B   
68            68            68         532        0.1               A   
69            69            69         533        0.2               A   

     LATITUDE   LONGITUDE  STATE  START_DATE  END_DATE    FIPS      DATE  \
0   39.735278 -121.336389      6    20080621  20080831  6007.0  20080621   
1   39.533339 -121.530711      6    20010808  20010808  6007.0  20010808   
2   39.355089 -121.772239      6    20041012  20041012  6007.0  20041012   
3   39.790389 -121.515500      6    20041011  20041011  6007.0  20041011   
4   39.777800 -121.552470      6    20080621  20080729  6007.0  20080621   
..        ...         ...    ...         ...       ...     ...       ...   
65  39.703289 -121.529600      6    20050910  20050910  6007.0  20050910   
66  39.836600 -121.624400      6    20030705  20030705  6007.0  20030705   
67  39.490500 -121.323969      6    20020215  20020215  6007.0  20020215   
68  39.851500 -121.685050      6    19990505  19990505  6007.0  19990505   
69  39.866031 -121.684231      6    19990506  19990506  6007.0  19990506   

    tmax  tmin  tavg  prcp       aws  fmc  
0    389   222   306     0  1.245353   96  
1    411   228   322     0  2.611998    0  
2    328   133   233     0  3.008472    0  
3    322   133   228     0  5.034409    0  
4    389   222   306     0  1.245353   96  
..   ...   ...   ...   ...       ...  ...  
65   389   222   306     0  4.138236   80  
66   367   189   278     0  3.549707    0  
67   139    72   106     3  2.758727    0  
68   283    72   178     0  1.345358    0  
69   289   122   206     0  2.249716    0  

[70 rows x 18 columns]

In [8]:
calaveras.head(30)

Unnamed: 0.7  Unnamed: 0.6  Unnamed: 0.5  Unnamed: 0.4  Unnamed: 0.3  \
0              0             0             0             0             0   
1              1             1             1             1             1   
2              2             2             2             2             2   
3              3             3             3             3             3   
4              4             4             4             4             4   
5              5             5             5             5             5   
6              6             6             6             6             6   
7              7             7             7             7             7   
8              8             8             8             8             8   
9              9             9             9             9             9   
10            10            10            10            10            10   
11            11            11            11            11            11   
12            12            12            12            12            12   
13            13            13            13            13            13   
14            14            14            14            14            14   
15            15            15            15            15            15   
16            16            16            16            16            16   
17            17            17            17            17            17   
18            18            18            18            18            18   
19            19            19            19            19            19   
20            20            20            20            20            20   
21            21            21            21            21            21   
22            22            22            22            22            22   
23            23            23            23            23            23   
24            24            24            24            24            24   
25            25            25            25            25            25   
26            26            26            26            26            26   
27            27            27            27            27            27   
28            28            28            28            28            28   
29            29            29            29            29            29   

    Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  FIRE_SIZE FIRE_SIZE_CLASS  ...  \
0              0             0           0       1.00               B  ...   
1              1             1           1       0.50               B  ...   
2              2             2           2       0.10               A  ...   
3              3             3           3       1.00               B  ...   
4              4             4           4       0.10               A  ...   
5              5             5           5       0.10               A  ...   
6              6             6           6     135.00               D  ...   
7              7             7           7       4.00               B  ...   
8              8             8           8       0.10               A  ...   
9              9             9           9       4.00               B  ...   
10            10            10          10       0.25               A  ...   
11            11            11          11       2.00               B  ...   
12            12            12          12       0.10               A  ...   
13            13            13          13       0.10               A  ...   
14            14            14          14       0.10               A  ...   
15            15            15          15       0.10               A  ...   
16            16            16          16       0.10               A  ...   
17            17            17          17       0.10               A  ...   
18            18            18          18       0.20               A  ...   
19            19            19          19       0.10               A  ...   
20       

In [9]:
fresno.head(30)

Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  FIRE_SIZE  \
0              0             0             0        3160       0.10   
1              1             1             1        3161       0.10   
2              2             2             2        3162       0.10   
3              3             3             3        3163       0.50   
4              4             4             4        3164    7456.00   
5              5             5             5        3165       0.20   
6              6             6             6        3166       0.01   
7              7             7             7        3167       0.33   
8              8             8             8        3168       0.10   
9              9             9             9        3169       0.10   
10            10            10            10        3170       3.00   
11            11            11            11        3171      26.00   
12            12            12            12        3172       0.20   
13            13            13            13        3173       0.25   
14            14            14            14        3174       0.10   
15            15            15            15        3175       2.00   
16            16            16            16        3176       0.10   
17            17            17            17        3177       0.10   
18            18            18            18        3178       2.00   
19            19            19            19        3179       0.10   
20            20            20            20        3180       0.10   
21            21            21            21        3181       0.10   
22            22            22            22        3182       0.10   
23            23            23            23        3183       0.10   
24            24            24            24        3184       1.00   
25            25            25            25        3185       0.10   
26            26            26            26        3186       0.10   
27            27            27            27        3187       0.10   
28            28            28            28        3188      15.00   
29            29            29            29        3189       0.10   

   FIRE_SIZE_CLASS   LATITUDE   LONGITUDE  STATE  START_DATE  END_DATE  \
0                A  37.271389 -119.182222      6    20060722  20060723   
1                A  37.419167 -118.966389      6    20060626  20060627   
2                A  37.017075 -119.611833      6    20071214  20071214   
3                B  37.235833 -118.993056      6    20070806  20070807   
4                G  36.903611 -118.801111      6    20080725  20081212   
5                A  37.444444 -119.120000      6    20060721  20060721   
6                A  37.110278 -119.114167      6    20070918  20070918   
7                B  36.795833 -118.898611      6    20060709  20060709   
8                A  36.086761 -120.119919      6    20010703  20010703   
9                A  37.086111 -119.216667      6    20080902  20080902   
10               B  36.110900 -120.565100      6    20050604  20050604   
11               C  36.071700 -120.316489      6    20030725  20030726   
12               A  37.278611 -118.968889      6    20060719  20060719   
13               A  35.693333 -118.009722      6    20080325  20080325   
14               A  37.017700 -119.574050      6    20000625  20000625   
15               B  36.110900 -120.565100      6    20050604  20050604   
16               A  36.110900 -120.565100      6    20050605  20050605   
17               A  37.325000 -118.866944      6    20080913  20080914   
18               B  36.216689 -120.453361      6    20030826  20030826   
19               A  37.293056 -119.036667      6    20060721  20060722   
20               A  37.299722 -119.117222      6    20080728  20080728   
21               A  37.411667 -119.067778      6    20060626  20060626   
22               A  37.259167 -119.142222      6    20070812  20070812   
23               A  36.076

In [10]:
humboldt.head(3)

Unnamed: 0.5  Unnamed: 0.4  Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  \
0             0             0             0             0             0   
1             1             1             1             1             1   
2             2             2             2             2             2   

   Unnamed: 0  FIRE_SIZE FIRE_SIZE_CLASS   LATITUDE   LONGITUDE  ...  \
0        3615        0.2               A  40.908611 -123.615278  ...   
1        3616        1.0               B  40.032119 -124.047669  ...   
2        3617      903.0               E  40.399400 -123.949400  ...   

   START_DATE  END_DATE    FIPS      DATE  tmax  tmin  tavg  prcp       aws  \
0    20060917  20060917  6023.0  20060917   150   111   133     0  5.449113   
1    20070401  20070401  6023.0  20070401   150   111   133     0  3.404772   
2    20080621  20080718  6023.0  20080621   150   111   133     0  2.274308   

     fmc  
0  103.0  
1  139.0  
2   62.0  

[3 rows x 21 columns]

In [11]:
kern.head(3)

Unnamed: 0.1  Unnamed: 0  FIRE_SIZE FIRE_SIZE_CLASS   LATITUDE   LONGITUDE  \
0             0        4302       75.0               C  35.176956 -119.540608   
1             1        4303     1223.0               F  35.305144 -118.666681   
2             2        4304       80.0               C  34.921944 -119.404722   

   STATE  START_DATE  END_DATE    FIPS      DATE  tmax  tmin  tavg  prcp  \
0      6    20050804  20050804  6029.0  20050804   400   244   322     0   
1      6    20030616  20030616  6029.0  20030616   361   200   283     0   
2      6    20080516  20080517  6029.0  20080516   400   244   322     0   

        aws   fmc  
0  1.650767  64.5  
1  1.646940  81.5  
2  2.450184  82.0

In [12]:
lassen.head(30)

Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  FIRE_SIZE  \
0              0             0             0        5809       1.75   
1              1             1             1        5810       5.00   
2              2             2             2        5811       0.10   
3              3             3             3        5812       0.10   
4              4             4             4        5813       0.20   
5              5             5             5        5814       0.10   
6              6             6             6        5815       0.50   
7              7             7             7        5816       0.50   
8              8             8             8        5817       0.20   
9              9             9             9        5818       0.10   
10            10            10            10        5819       0.10   
11            11            11            11        5820      65.30   
12            12            12            12        5821       0.10   
13            13            13            13        5822       5.00   
14            14            14            14        5823       0.60   
15            15            15            15        5824      35.00   
16            16            16            16        5825       0.10   
17            17            17            17        5826       0.10   
18            18            18            18        5827       0.10   
19            19            19            19        5828       2.90   
20            20            20            20        5829     175.00   
21            21            21            21        5830      51.00   
22            22            22            22        5831       1.75   
23            23            23            23        5832       0.10   
24            24            24            24        5833       3.20   
25            25            25            25        5834       0.10   
26            26            26            26        5835       1.00   
27            27            27            27        5836       0.10   
28            28            28            28        5837       0.50   
29            29            29            29        5838       0.10   

   FIRE_SIZE_CLASS   LATITUDE   LONGITUDE  STATE  START_DATE  END_DATE  \
0                B  40.899167 -121.225278      6    20090802  20090802   
1                B  40.473200 -120.477700      6    20020723  20020724   
2                A  40.999722 -121.399722      6    20090802  20090805   
3                A  40.488056 -120.615778      6    20050908  20050908   
4                A  40.057500 -120.051700      6    20050909  20050909   
5                A  40.983200 -121.326100      6    20040814  20040814   
6                B  41.000300 -120.550300      6    20050909  20050910   
7                B  40.532861 -120.758119      6    20040524  20040524   
8                A  40.487400 -120.513800      6    20040814  20040815   
9                A  40.779900 -120.534400      6    20020718  20020718   
10               A  39.925600 -120.008300      6    20090801  20090801   
11               A  40.956400 -121.187800      6    20090802  20090802   
12               A  40.671900 -120.565800      6    20070620  20070620   
13               B  40.965600 -121.232500      6    20090802  20090802   
14               B  40.895600 -121.000800      6    20090803  20090803   
15               C  40.959400 -121.256100      6    20090802  20090804   
16               A  40.532461 -120.666769      6    20040521  20040521   
17               A  41.102889 -120.903800      6    20040814  20040814   
18               A  40.962200 -121.200000      6    20090801  20090802   
19               B  40.808333 -121.199444      6    20070831  20070901   
20               D  40.684722 -120.999722      6    20090802  20090802   
21               C  40.006570 -120.066040      6    19990605  19990605   
22               B  40.616389 -120.799722      6    20090802  20090806   
23               A  40.329

In [13]:
modoc.head(30)

Unnamed: 0.9  Unnamed: 0.8  Unnamed: 0.7  Unnamed: 0.6  Unnamed: 0.5  \
0              0             0             0             0             0   
1              1             1             1             1             1   
2              2             2             2             2             2   
3              3             3             3             3             3   
4              4             4             4             4             4   
5              5             5             5             5             5   
6              6             6             6             6             6   
7              7             7             7             7             7   
8              8             8             8             8             8   
9              9             9             9             9             9   
10            10            10            10            10            10   
11            11            11            11            11            11   
12            12            12            12            12            12   
13            13            13            13            13            13   
14            14            14            14            14            14   
15            15            15            15            15            15   
16            16            16            16            16            16   
17            17            17            17            17            17   
18            18            18            18            18            18   
19            19            19            19            19            19   
20            20            20            20            20            20   
21            21            21            21            21            21   
22            22            22            22            22            22   
23            23            23            23            23            23   
24            24            24            24            24            24   
25            25            25            25            25            25   
26            26            26            26            26            26   
27            27            27            27            27            27   
28            28            28            28            28            28   
29            29            29            29            29            29   

    Unnamed: 0.4  Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  ...  \
0              0             0             0             0        8193  ...   
1              1             1             1             1        8194  ...   
2              2             2             2             2        8195  ...   
3              3             3             3             3        8196  ...   
4              4             4             4             4        8197  ...   
5              5             5             5             5        8198  ...   
6              6             6             6             6        8199  ...   
7              7             7             7             7        8200  ...   
8              8             8             8             8        8201  ...   
9              9             9             9             9        8202  ...   
10            10            10            10            10        8203  ...   
11            11            11            11            11        8204  ...   
12            12            12            12            12        8205  ...   
13            13            13            13            13        8206  ...   
14            14            14            14            14        8207  ...   
15            15            15            15            15        8208  ...   
16            16            16            16            16        8209  ...   
17            17            17            17            17        8210  ...   
18            18            18            18            18        8211  ...   
19            19            19            19            19        8

In [14]:
dorado.head(3)

Unnamed: 0  FIRE_SIZE FIRE_SIZE_CLASS   LATITUDE   LONGITUDE  STATE  \
0        1793        0.1               A  38.649819 -120.938639      6   
1        1794        0.1               A  38.705000 -120.587222      6   
2        1795        0.1               A  38.773411 -120.811150      6   

   START_DATE  END_DATE    FIPS      DATE  tmax  tmin  tavg  prcp       aws  \
0    20020508  20020508  6017.0  20020508   144   -35    35     0  2.786203   
1    20080604  20080604  6017.0  20080604    85    25    51     0  5.624106   
2    20040416  20040416  6017.0  20040416    61   -36     6     0  2.383996   

     fmc  
0  172.0  
1   70.0  
2  206.0

In [15]:
nevada.head(3)

Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  FIRE_SIZE FIRE_SIZE_CLASS  \
0             0             0        9300       10.0               C   
1             1             1        9301        0.1               A   
2             2             2        9302        0.2               A   

    LATITUDE   LONGITUDE  STATE  START_DATE  END_DATE    FIPS      DATE  tmax  \
0  39.036950 -121.123203      6    20070121  20070121  6057.0  20070121    -1   
1  39.365289 -121.124769      6    20040828  20040828  6057.0  20040828   260   
2  39.123450 -121.075389      6    19980809  19980809  6057.0  19980809   232   

   tmin  tavg  prcp       aws    fmc  
0   -74   -46     0  1.764761  76.25  
1    74   157     0  0.723467  61.00  
2    64   152     0  2.607683  99.75

In [16]:
plumas.head(3)

Unnamed: 0.6  Unnamed: 0.5  Unnamed: 0.4  Unnamed: 0.3  Unnamed: 0.2  \
0             0             0             0             0             0   
1             1             1             1             1             1   
2             2             2             2             2             2   

   Unnamed: 0.1  Unnamed: 0  FIRE_SIZE FIRE_SIZE_CLASS   LATITUDE  ...  \
0             0       10570       0.10               A  39.899722  ...   
1             1       10571       0.25               A  40.145833  ...   
2             2       10572       0.90               B  40.185000  ...   

   START_DATE  END_DATE    FIPS      DATE  tmax  tmin  tavg  prcp       aws  \
0    20060811  20060811  6063.0  20060811   243    35   137     0  1.813398   
1    20060709  20060709  6063.0  20060709   239    89   159     0  0.609016   
2    20091108  20091108  6063.0  20091108   107   -89    -8     0  1.569229   

   fmc  
0   99  
1   99  
2   94  

[3 rows x 22 columns]

In [17]:
riverside.head(3)

Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  FIRE_SIZE  \
0             0             0             0           0        0.1   
1             1             1             1           1        1.0   
2             2             2             2           2        0.1   

  FIRE_SIZE_CLASS   LATITUDE   LONGITUDE  STATE  START_DATE  END_DATE    FIPS  \
0               A  33.976008 -116.501361      6    20070616  20070616  6065.0   
1               B  33.735631 -117.266681      6    20031014  20031014  6065.0   
2               A  33.663369 -116.312561      6    19990202  19990202  6065.0   

       DATE   tmax   tmin   tavg  prcp       aws     fmc  
0  20070616  406.0  294.0  350.0   0.0  3.773714  67.077  
1  20031014  356.0  211.0  283.0   0.0  1.278828  67.500  
2  19990202  228.0   50.0  139.0   0.0  4.756914  60.667

In [18]:
bernardino.head(3)

Unnamed: 0.1  Unnamed: 0  FIRE_SIZE FIRE_SIZE_CLASS   LATITUDE   LONGITUDE  \
0             0       13745       0.10               A  35.393300 -115.827800   
1             1       13746       0.10               A  34.279722 -116.845833   
2             2       13747       0.02               A  34.216389 -116.889167   

   STATE  START_DATE  END_DATE    FIPS      DATE  tmax  tmin  tavg  prcp  \
0      6    20070810  20070810  6071.0  20070810   439   322   383     0   
1      6    20091113  20091113  6071.0  20091113   439   322   383     0   
2      6    20070812  20070812  6071.0  20070812   439   322   383     0   

        aws      fmc  
0  2.844799   58.615  
1  2.091634  109.333  
2  2.214722   67.000

In [19]:
diego.head(3)

Unnamed: 0  FIRE_SIZE FIRE_SIZE_CLASS   LATITUDE   LONGITUDE  STATE  \
0       14726        0.1               A  32.661481 -116.598631      6   
1       14727        3.0               B  32.721389 -116.557778      6   
2       14728        0.3               B  32.657803 -116.458650      6   

   START_DATE  END_DATE    FIPS      DATE  tmax  tmin  tavg  prcp       aws  \
0    20041211  20041211  6073.0  20041211   239    56   150     0  3.234333   
1    19990108  19990109  6073.0  19990108   178    50   117     0  3.375749   
2    20050601  20050601  6073.0  20050601   250    89   172     0  3.575618   

      fmc  
0  72.000  
1   0.000  
2  89.667

In [177]:
shasta.head(3)

Unnamed: 0  FIRE_SIZE FIRE_SIZE_CLASS   LATITUDE   LONGITUDE  STATE  \
0       15990        0.1               A  40.607406 -122.496061      6   
1       15991        0.1               A  40.716389 -121.423889      6   
2       15992        0.5               B  40.497081 -122.360719      6   

   START_DATE  END_DATE    FIPS      DATE  tmax  tmin  tavg  prcp       aws  \
0    20060618  20060618  6089.0  20060618   394   217   306     0  2.997146   
1    20070710  20070711  6089.0  20070710   394   217   306     0  1.721920   
2    19980703  19980703  6089.0  19980703   333   161   250     0  4.217491   

     fmc  
0  118.5  
1   72.5  
2    0.0

In [21]:
siskiyou.head(3)

Unnamed: 0  FIRE_SIZE FIRE_SIZE_CLASS   LATITUDE   LONGITUDE  STATE  \
0       17144        1.5               B  41.574500 -122.643311      6   
1       17145        0.2               A  41.502239 -122.737850      6   
2       17154        0.1               A  41.719639 -122.757569      6   

   START_DATE  END_DATE    FIPS      DATE  tmax  tmin  tavg  prcp       aws  \
0    20020818  20020819  6093.0  20020818   317    94   206     0  1.686797   
1    20020722  20020722  6093.0  20020722   283   139   211     0  3.466604   
2    20020722  20020722  6093.0  20020722   283   139   211     0  3.466604   

       fmc  
0  103.333  
1  130.000  
2  130.000

In [7]:
fire_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14151 entries, 0 to 14150
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Unnamed: 0.2     6999 non-null   float64
 1   Unnamed: 0.1     9219 non-null   float64
 2   Unnamed: 0       14151 non-null  int64  
 3   FIRE_SIZE        14151 non-null  float64
 4   FIRE_SIZE_CLASS  14151 non-null  object 
 5   LATITUDE         14151 non-null  float64
 6   LONGITUDE        14151 non-null  float64
 7   STATE            14151 non-null  int64  
 8   START_DATE       14151 non-null  int64  
 9   END_DATE         14151 non-null  int64  
 10  FIPS             14151 non-null  float64
 11  DATE             14151 non-null  int64  
 12  tmax             14137 non-null  float64
 13  tmin             14137 non-null  float64
 14  tavg             14137 non-null  float64
 15  prcp             14137 non-null  float64
 16  aws              14151 non-null  float64
 17  fmc         

In [178]:
fire_data.head(500)

FIRE_SIZE_CLASS   LATITUDE   LONGITUDE    FIPS        DATE   tmax   tmin  \
0                  1  39.735278 -121.336389  6007.0  20080621.0  389.0  222.0   
1                  1  39.533339 -121.530711  6007.0  20010808.0  411.0  228.0   
2                  1  39.355089 -121.772239  6007.0  20041012.0  328.0  133.0   
3                  1  39.790389 -121.515500  6007.0  20041011.0  322.0  133.0   
4                  2  39.777800 -121.552470  6007.0  20080621.0  389.0  222.0   
..               ...        ...         ...     ...         ...    ...    ...   
495                1  39.921469 -121.728597  6007.0  20070228.0  389.0  222.0   
496                1  39.572953 -121.313275  6007.0  20070401.0  389.0  222.0   
497                1  39.980181 -121.550731  6007.0  20040625.0  333.0  161.0   
498                1  39.849939 -121.588689  6007.0  19980726.0  383.0  211.0   
499                1  39.925469 -121.724111  6007.0  20030629.0  361.0  178.0   

      tavg  prcp       aws    fmc  
0    306.0   0.0  1.245353   96.0  
1    322.0   0.0  2.611998    0.0  
2    233.0   0.0  3.008472    0.0  
3    228.0   0.0  5.034409    0.0  
4    306.0   0.0  1.245353   96.0  
..     ...   ...       ...    ...  
495  306.0   0.0  3.104664  110.0  
496  306.0   0.0  1.793009  102.0  
497  250.0   0.0  4.080243    0.0  
498  300.0   0.0  1.055472    0.0  
499  272.0   0.0  3.184797    0.0  

[500 rows x 11 columns]

In [213]:
fire_data.drop(["Unnamed: 0.3"], axis = 1, inplace = True)
fire_data.drop(["Unnamed: 0.2"], axis = 1, inplace = True)
fire_data.drop(["Unnamed: 0.1"], axis = 1, inplace = True)
fire_data.drop(["Unnamed: 0"], axis = 1, inplace = True)
fire_data.drop(["STATE"], axis = 1, inplace = True)
fire_data.drop(["START_DATE"], axis = 1, inplace = True)
fire_data.drop(["END_DATE"], axis = 1, inplace = True)



In [214]:
fire_data.drop(["Unnamed: 0.4"], axis = 1, inplace = True)
fire_data.drop(["Unnamed: 0.5"], axis = 1, inplace = True)
fire_data.drop(["Unnamed: 0.6"], axis = 1, inplace = True)
fire_data.drop(["Unnamed: 0.7"], axis = 1, inplace = True)
fire_data.drop(["Unnamed: 0.8"], axis = 1, inplace = True)
fire_data.drop(["Unnamed: 0.9"], axis = 1, inplace = True)

In [215]:
def classify_ranges(df, column_name, ranges, classification_column):
    for range_name, range_values in ranges.items():
        df.loc[df[column_name].between(*range_values), classification_column] = range_name

# Example usage


classification_ranges = {
    'A': (0, 0.25),
    'B': (0.2600000001, 9),
    'C': (9.000000001, 99),
    'D': (99.000000001, 299),
    'E': (299.000000001, 999),
    'F': (999.000000001, 4999),
    'G': (4999.000000001, 10000),
    'G': (10000.000000001, 1000000000)

}
  # Creating a new column to store the classifications
classify_ranges(fire_data, 'FIRE_SIZE', classification_ranges, 'FIRE_SIZE_CLASS')


In [115]:
def classify_ranges(df, column_name, ranges, classification_column):
    for range_name, range_values in ranges.items():
        df.loc[df[column_name].between(*range_values), classification_column] = range_name

# Example usage


classification_ranges = {
    'A': (0, 99),
    'B': (100, 999),
    'C': (1000, 999999999)



}
  # Creating a new column to store the classifications
classify_ranges(fire_data, 'FIRE_SIZE', classification_ranges, 'FIRE_SIZE_CLASS')


In [239]:
fire_data.drop(["FIRE_SIZE"], axis = 1, inplace = True)

In [117]:
fire_data.groupby("FIRE_SIZE_CLASS").count()

LATITUDE  LONGITUDE   FIPS   DATE   tmax   tmin   tavg  \
FIRE_SIZE_CLASS                                                           
A                   13796      13796  13796  13796  13782  13782  13782   
B                     240        240    240    240    240    240    240   
C                     115        115    115    115    115    115    115   

                  prcp    aws    fmc  
FIRE_SIZE_CLASS                       
A                13782  13796  13796  
B                  240    240    240  
C                  115    115    115

In [118]:
fire_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14151 entries, 0 to 14150
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   FIRE_SIZE_CLASS  14151 non-null  object 
 1   LATITUDE         14151 non-null  float64
 2   LONGITUDE        14151 non-null  float64
 3   FIPS             14151 non-null  float64
 4   DATE             14151 non-null  int64  
 5   tmax             14137 non-null  float64
 6   tmin             14137 non-null  float64
 7   tavg             14137 non-null  float64
 8   prcp             14137 non-null  float64
 9   aws              14151 non-null  float64
 10  fmc              14151 non-null  float64
dtypes: float64(9), int64(1), object(1)
memory usage: 1.2+ MB


In [216]:
fire_data.dropna(inplace = True)
fire_data['FIRE_SIZE_CLASS'] = fire_data['FIRE_SIZE_CLASS'].replace({'A':1 , 'B':2 , 'C':3 ,'D':4 , 'E':5 , 'F':6 , 'G':7 })

In [120]:
fire_data["DATE"] = fire_data["DATE"].astype(float)

In [121]:
x = fire_data.drop("FIRE_SIZE_CLASS", axis=1)
y = fire_data["FIRE_SIZE_CLASS"]

In [168]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = .3, random_state = 101)

In [169]:
X_train = torch.tensor(X_train.values, dtype = torch.float)
Y_train = torch.tensor(Y_train.values, dtype = torch.int64)
X_test = torch.tensor(X_test.values, dtype = torch.float)
Y_test = torch.tensor(Y_test.values, dtype = torch.int64)

In [170]:
class NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork, self).__init__()
    self.hidden1 = nn.Linear(X_train.shape[1], 16)
    self.hidden2 = nn.Linear(16, 1)


  def forward(self, x):
    x = torch.relu(self.hidden1(x))
    x = self.hidden2(x)
    return x

In [171]:
model = NeuralNetwork()
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), .0005)
print(model)

NeuralNetwork(
  (hidden1): Linear(in_features=10, out_features=16, bias=True)
  (hidden2): Linear(in_features=16, out_features=1, bias=True)
)


In [21]:
#Y_train = torch.flatten(Y_train)
#Y_test = torch.flatten(Y_test)

In [172]:
train_data = TensorDataset(X_train, Y_train)
train_loader = DataLoader(train_data, batch_size = 32)

In [173]:
epochs = 10
loss_list = np.zeros((epochs,))

for epoch in range(epochs):
  running_loss = 0
  for inputs, targets in train_loader:
    optimizer.zero_grad() # reset optimizer gradients
    outputs = model(inputs) # forward pass data through nodes and layers
    outputs = torch.flatten(outputs)
    loss = loss_fn(outputs, targets.float()) # compute loss
    loss_list[epoch] = loss.item()
    running_loss += loss.item()
    loss.backward() #backpropagation
    optimizer.step() # update weights

  if epoch%10 == 0:
    print(f"Epoch [{epoch}/10000], Loss: {running_loss/len(train_loader)}")

Epoch [0/10000], Loss: 5548.31165382939


In [174]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import f1_score
model.eval()

with torch.no_grad():
  out = model(X_test)
  print(Y_test)
  _, predicted = torch.max(out.data, 1)
  print(predicted)
  total = Y_test.size(0)
  correct = (predicted == Y_test).sum().item()
  print("Accuracy of the model based on y_test: {}%".format(100 * correct/total))



tensor([2, 1, 1,  ..., 1, 1, 1])
tensor([0, 0, 0,  ..., 0, 0, 0])
Accuracy of the model based on y_test: 0.0%


In [131]:
print(predicted)

tensor([0, 0, 0,  ..., 0, 0, 0])


In [176]:
predictions

tensor([193.6488, 193.3363, 193.9925,  ..., 194.1488, 193.5550, 194.1175])

In [85]:
Y_test

tensor([1, 0, 0,  ..., 0, 0, 0])

In [175]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import f1_score
model.eval()

with torch.no_grad():
    outputs = model(X_test)
    predictions = outputs.flatten().tolist()
    actuals = Y_test.tolist()

predictions = torch.tensor(predictions)
actuals = torch.tensor(actuals)

mse = mean_squared_error(actuals, predictions)
r2 = r2_score(actuals, predictions)
rmse = np.sqrt(mse)

print('Test MSE:', mse)
print("Test r2:", r2)
print('Test RMSE:', rmse)


Test MSE: 37207.458418213544
Test r2: -754295.8551817912
Test RMSE: 192.89234929932692


In [72]:
predictions

tensor([36128.6172, 36035.3672, 36186.4922,  ..., 36203.9922, 36051.2422,
        36223.3672])

In [43]:
Y_test

tensor([2, 1, 1,  ..., 1, 1, 1])

In [102]:
print(classification_report(predictions, Y_test))

ValueError: ignored

In [88]:
from sklearn.metrics import classification_report
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score


In [89]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [103]:
fire_data.groupby("FIRE_SIZE_CLASS").count()

LATITUDE  LONGITUDE   FIPS   DATE   tmax   tmin   tavg  \
FIRE_SIZE_CLASS                                                           
1                   13782      13782  13782  13782  13782  13782  13782   
2                     240        240    240    240    240    240    240   
3                      94         94     94     94     94     94     94   
4                      21         21     21     21     21     21     21   

                  prcp    aws    fmc  
FIRE_SIZE_CLASS                       
1                13782  13782  13782  
2                  240    240    240  
3                   94     94     94  
4                   21     21     21

In [185]:
fire_data.head(100)

FIRE_SIZE_CLASS   LATITUDE   LONGITUDE    FIPS        DATE   tmax   tmin  \
0                 1  39.735278 -121.336389  6007.0  20080621.0  389.0  222.0   
1                 1  39.533339 -121.530711  6007.0  20010808.0  411.0  228.0   
2                 1  39.355089 -121.772239  6007.0  20041012.0  328.0  133.0   
3                 1  39.790389 -121.515500  6007.0  20041011.0  322.0  133.0   
4                 2  39.777800 -121.552470  6007.0  20080621.0  389.0  222.0   
..              ...        ...         ...     ...         ...    ...    ...   
95                1  39.354961 -121.790100  6007.0  20000612.0  311.0  183.0   
96                1  39.713872 -121.711642  6007.0  20070610.0  389.0  222.0   
97                1  39.912242 -121.601475  6007.0  20070916.0  389.0  222.0   
98                1  39.919900 -121.612800  6007.0  20030831.0  356.0  189.0   
99                1  39.563981 -121.324731  6007.0  20000628.0  378.0  222.0   

     tavg  prcp       aws   fmc  
0   306.0   0.0  1.245353  96.0  
1   322.0   0.0  2.611998   0.0  
2   233.0   0.0  3.008472   0.0  
3   228.0   0.0  5.034409   0.0  
4   306.0   0.0  1.245353  96.0  
..    ...   ...       ...   ...  
95  250.0   0.0  2.573788   0.0  
96  306.0   0.0  3.382810  72.0  
97  306.0   0.0  3.554614  90.0  
98  272.0   0.0  1.094029   0.0  
99  300.0   0.0  2.538865   0.0  

[100 rows x 11 columns]

In [186]:
fire_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14137 entries, 0 to 14150
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   FIRE_SIZE_CLASS  14137 non-null  int64  
 1   LATITUDE         14137 non-null  float64
 2   LONGITUDE        14137 non-null  float64
 3   FIPS             14137 non-null  float64
 4   DATE             14137 non-null  float64
 5   tmax             14137 non-null  float64
 6   tmin             14137 non-null  float64
 7   tavg             14137 non-null  float64
 8   prcp             14137 non-null  float64
 9   aws              14137 non-null  float64
 10  fmc              14137 non-null  float64
dtypes: float64(10), int64(1)
memory usage: 1.3 MB


In [247]:
x = fire_data.drop("FIRE_SIZE_CLASS", axis=1)
y = fire_data["FIRE_SIZE_CLASS"]

In [263]:

# Sample DataFrame

df = fire_data

# Value to check and remove
value_to_remove = 1
column_to_check = 'FIRE_SIZE_CLASS'

# Check for value in the specified column and remove the corresponding row
if value_to_remove in df[column_to_check].values:
    fire_data1 = df[df[column_to_check] != value_to_remove]
    print(f"Removed rows with {value_to_remove} in {column_to_check} column:\n{df}")
else:
    print(f"{value_to_remove} not found in {column_to_check} column")

# Print the updated DataFrame
print("Updated DataFrame:")
print(df)

Removed rows with 1 in FIRE_SIZE_CLASS column:
       FIRE_SIZE_CLASS   LATITUDE   LONGITUDE    FIPS      DATE   tmax   tmin  \
0                    2  39.735278 -121.336389  6007.0  20080621  389.0  222.0   
1                    2  39.533339 -121.530711  6007.0  20010808  411.0  228.0   
2                    3  39.355089 -121.772239  6007.0  20041012  328.0  133.0   
3                    1  39.790389 -121.515500  6007.0  20041011  322.0  133.0   
4                    5  39.777800 -121.552470  6007.0  20080621  389.0  222.0   
...                ...        ...         ...     ...       ...    ...    ...   
14146                1  41.593239 -122.964950  6093.0  19980809  300.0   83.0   
14147                1  41.692989 -122.944450  6093.0  19990811  217.0   94.0   
14148                1  41.894319 -122.565000  6093.0  19980818  256.0   72.0   
14149                1  41.815219 -121.928339  6093.0  20030707  317.0  111.0   
14150                2  41.901689 -121.850519  6093.0  1998081

In [190]:
fire_data1.head()

FIRE_SIZE_CLASS   LATITUDE   LONGITUDE    FIPS        DATE   tmax   tmin  \
4                  2  39.777800 -121.552470  6007.0  20080621.0  389.0  222.0   
46                 2  39.355089 -121.772239  6007.0  20041011.0  322.0  133.0   
57                 2  39.704950 -121.702889  6007.0  20041011.0  322.0  133.0   
108                3  39.591000 -121.512169  6007.0  20040811.0  400.0  178.0   
192                2  39.548200 -121.531100  6007.0  20040812.0  389.0  206.0   

      tavg  prcp       aws   fmc  
4    306.0   0.0  1.245353  96.0  
46   228.0   0.0  5.034409   0.0  
57   228.0   0.0  5.034409   0.0  
108  289.0   0.0  2.404692   0.0  
192  300.0   0.0  3.032787   0.0

In [197]:
fire_data1.groupby("FIRE_SIZE_CLASS").count()


LATITUDE  LONGITUDE  FIPS  DATE  tmax  tmin  tavg  prcp  aws  \
FIRE_SIZE_CLASS                                                                 
2                     240        240   240   240   240   240   240   240  240   
3                     115        115   115   115   115   115   115   115  115   

                 fmc  
FIRE_SIZE_CLASS       
2                240  
3                115

In [264]:
x = fire_data1.drop("FIRE_SIZE_CLASS", axis=1)
y = fire_data1["FIRE_SIZE_CLASS"]

In [265]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.20, random_state = 101)

In [266]:
lm = LogisticRegression()
lm.fit(X_train, Y_train)

LogisticRegression()

In [267]:
predictions = lm.predict(X_test)

In [268]:
mean_squared_error(Y_test, predictions)

0.7439353099730458

In [269]:
print(classification_report(Y_test, predictions))

              precision    recall  f1-score   support

           2       0.83      1.00      0.91       921
           3       0.00      0.00      0.00       123
           4       0.00      0.00      0.00        27
           5       0.00      0.00      0.00        21
           6       0.00      0.00      0.00        13
           7       0.00      0.00      0.00         8

    accuracy                           0.83      1113
   macro avg       0.14      0.17      0.15      1113
weighted avg       0.68      0.83      0.75      1113



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [270]:
print(confusion_matrix(Y_test, predictions))

[[921   0   0   0   0   0]
 [123   0   0   0   0   0]
 [ 27   0   0   0   0   0]
 [ 21   0   0   0   0   0]
 [ 13   0   0   0   0   0]
 [  8   0   0   0   0   0]]


In [224]:
print(accuracy_score(Y_test, predictions))

0.5993635077793493


In [200]:
from sklearn import metrics

In [225]:
mean_squared_error(Y_test, predictions)

0.9550919377652051

In [254]:
r2_score(Y_test, predictions)

-0.40129264663445374

In [271]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train, Y_train)

DecisionTreeClassifier()

In [272]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [273]:
y_pred_dtc = dtc.predict(X_test)

In [274]:
X_test

LATITUDE   LONGITUDE    FIPS      DATE   tmax   tmin   tavg  prcp  \
5360   41.530000 -120.858333  6049.0  20070531  260.0   43.0  157.0   0.0   
3096   41.306944 -123.549167  6023.0  20081016  150.0  111.0  133.0   0.0   
121    39.519100 -121.380719  6007.0  20030828  333.0  156.0  244.0   0.0   
6519   38.585556 -120.430833  6017.0  20080621  228.0  120.0  164.0   0.0   
3740   35.298636 -119.623397  6029.0  20000515  256.0  122.0  189.0   3.0   
...          ...         ...     ...       ...    ...    ...    ...   ...   
5740   41.436600 -120.611100  6049.0  20010704  294.0  152.0  211.0   0.0   
5335   41.617500 -120.251944  6049.0  20060724  305.0  143.0  204.0   0.0   
13116  40.666667 -121.433333  6089.0  20090802  394.0  217.0  306.0   0.0   
7024   38.748831 -120.881439  6017.0  20040514  131.0  -19.0   50.0   0.0   
12707  32.891111 -116.453056  6073.0  20020727  306.0   94.0  200.0   0.0   

            aws      fmc  
5360   2.099146  124.250  
3096   6.674682  101.000  
121    3.189442    0.000  
6519   1.245353   81.333  
3740   2.373940   93.000  
...         ...      ...  
5740   2.524465   83.500  
5335   1.302462  111.333  
13116  3.851304  129.000  
7024   3.105951  106.000  
12707  1.961736   45.000  

[1113 rows x 10 columns]

In [275]:
print(classification_report(Y_test, y_pred_dtc))

              precision    recall  f1-score   support

           2       0.87      0.84      0.86       921
           3       0.22      0.26      0.24       123
           4       0.17      0.19      0.18        27
           5       0.03      0.05      0.04        21
           6       0.00      0.00      0.00        13
           7       0.00      0.00      0.00         8

    accuracy                           0.73      1113
   macro avg       0.22      0.22      0.22      1113
weighted avg       0.75      0.73      0.74      1113



In [276]:
print(confusion_matrix(Y_test, y_pred_dtc))


[[775 100  16  19   8   3]
 [ 72  32   3  10   4   2]
 [ 17   4   5   1   0   0]
 [ 11   4   3   1   0   2]
 [  8   3   2   0   0   0]
 [  4   3   1   0   0   0]]


In [277]:
print(accuracy_score(Y_test, y_pred_dtc))


0.7304582210242587


In [278]:
r2_score(Y_test, y_pred_dtc)

-0.7010377893361599